import Footer from "@/src/components/layout/Footer";
import "./globals.css";
import MainNavigation from "@/src/components/layout/MainNavigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
